version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    
  mongo:
    container_name: mongo
    image: mongo:5.0.6-focal
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=sample
      - TZ=Asia/Tokyo
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./mongo/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: mongo
        target: /data/db
        volume:
          nocopy: true
      - type: volume
        source: mongo
        target: /data/configdb
        volume:
          nocopy: true
volumes:
  mongo: